server:
  port: 8080
spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gateway:
      routes:
        - id: userservice_route
          uri: http://userservice:8090/
          predicates:
            - Path=/userservice/**
          filters:
#            - AddRequestHeader=X-Request-Id, 123
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}
        - id: authservice_route
          uri: http://authservice:8070/
          predicates:
            - Path=/authservice/**
          filters:
            - RewritePath=/authservice/(?<segment>.*), /$\{segment}
        - id: bookservice_route
          uri: http://bookservice:8095/
          predicates:
            - Path=/bookservice/**
          filters:
            - RewritePath=/bookservice/(?<segment>.*), /$\{segment}
        - id: recommendationservice_route
          uri: http://recommendationservice:8063/
          predicates:
            - Path=/recommendationservice/**
          filters:
            - RewritePath=/recommendationservice/(?<segment>.*), /$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#http://localhost:4200
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins:
#              - "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - HEAD
#              - OPTIONS
#            allowedHeaders:
#              - Accept
#              - Content-Type
#              - Origin
#              - X-Tenant
logging:
  level:
    org.springframework.cloud.gateway: INFO


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurekaserver:8085/eureka
#    register-with-eureka: true
#    fetch-registry: true
#
#ribbon:
#  eureka:
#    enabled: false
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always